export const UPDATE_SELECTED_SET = "UPDATE_SELECTED_SET";
export const UPDATE_SELECTED_BOXESSET = "UPDATE_SELECTED_BOXESSET";
export const UPDATE_SHOW_FILTER_KINGDOM = "UPDATE_SHOW_FILTER_KINGDOM";
export const UPDATE_FILTER_PLAYED_GAMES = "UPDATE_FILTER_PLAYED_GAMES";
export const UPDATE_FILTER_SET = "UPDATE_FILTER_SET";
export const UPDATE_NEED_REFRESH = "UPDATE_NEED_REFRESH";
export const UPDATE_SORT_SET = "UPDATE_SORT_SET";
export const UPDATE_SORT_BOXES_SET = "UPDATE_SORT_BOXES_SET"
